server:
  port: 8010


spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/movie_db
    username: movie
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

